### ISSUE TITLE
Not able to fetch any Real-Debrid links under 'My Downloads'

### ISSUE THREAD

**Issue by koelan** [MrMonkey42/stremio-addon-debrid-search#24]
Hello @MrMonkey42 

First of all, thank you for creating this add-on. It really serves my needs.

I just tried it today (both v0.1.8 and v0.1.5) with my Real-Debrid API, but it does not seem to be able to retrieve the existing links stored on my RD cloud i.e., links created outside of Stremio

On the other hand, when I watch some new videos on Stremio/Torrentio, those new video links will then appear under "Others-Debrid Search-ReadDebrid". 

Could it be a configuration issue? Did I miss any steps? I added the "Debrid Search" add-on to the end of the "My Addons" list after "Torrentio RD". Is the order of the add-ons relevant?

I am using Stremio 4.4.165.

Thank you for your help.

**Comment by MrMonkey42** [comment]
1. Are the existing links added via link downloader or torrent downloader? https://real-debrid.com/torrents or https://real-debrid.com/torrents
2. DebridSearch shows stream links based on movie/show IMDB name matching with the files downloaded on RD. Are the files in your RD in English or any other language?
3. Since the addon is at the end, any stream links shown by the addon will also be at the end. If you want DebridSearch streams to show up before Torrentio streams, you can reorder the addons via https://addon-manager.dontwanttos.top/

**Comment by koelan** [comment]
I realised that all links under "Torrents" display correctly. So all is good!

Originally I expect those other links under "My Downloads" would be displayed as well and hence the question. 

The add-on works well for me now! Thank you.
