### ISSUE TITLE
Alldebrid debrid search not working

### ISSUE THREAD

**Issue by oathzed** [MrMonkey42/stremio-addon-debrid-search#30]
Hello,

Basically debrid search is not working for alldebrid at all, it's erroring the catalog and it's also not picking up any of my "saved links" or "torrents" I have in my cloud.

I've tested with real debrid and that one has no issue.

Love the app, is it possible to get this fixed? Lemme know if you need help testing. Thanks!!

![Screenshot_20240625-134938](https://github.com/MrMonkey42/stremio-addon-debrid-search/assets/52545913/50e3e455-7806-4853-9fe8-79d904aba75b)

**Comment by DevonCM** [comment]
Same here, the addon isn't showing any results even though they're in my links history.  I'm not sure if this addon has just been abandoned or what.  It's too bad because this is necessary in conjunction with DMM to play through Stremio, otherwise you're limited to Torrentio's results which are often insufficient.

**Comment by oathzed** [comment]
> Is this issue still there for AllDebrid?

It works now!

Thank you!
